### ISSUE TITLE
关于汉典

### ISSUE THREAD

**Issue by tantingting1012** [bamtercelboo/corpus_process_script#4]
你好，运行基于汉典字符花时有点问题不能解决，好像是请求汉典部分失效了，请问您能方便更新一下吗，非常感谢。错误如下
From handian:    word 一 HTTPConnectionPool(host='www.zdic.net', port=80): Max retries exceeded with url: /sousuo/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8281219518>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by tantingting1012** [comment]
Extract Chinese Character Stoke Information
./Data/test.TempFound
 handling with the 1001 line, all -1 lines.
Handle Finished.
 handling with the 11 line, all 1824 lines.From handian:    word 人 url https://www.zdic.net/search/
'NoneType' object has no attribute 'contents'
All Finished.

**Comment by dalinvip** [comment]
嗯嗯，有些汉字会查不到
